; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_nrf52840_sense]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-afruitnrf52-nrf52840
framework = arduino
monitor_speed = 115200
build_flags = 
	-DXIAO
lib_deps =
    https://github.com/Seeed-Studio/Seeed_Arduino_LSM6DS3.git


[env:nice_nano]
platform = nordicnrf52
board = adafruit_feather_nrf52840
framework = arduino
monitor_speed = 115200
build_flags = 
	-DNICENANO
lib_deps =
    https://github.com/Seeed-Studio/Seeed_Arduino_LSM6DS3.git

[env:nrf52832_jlink]
platform = nordicnrf52
board = adafruit_feather_nrf52832
framework = arduino
upload_protocol = jlink
debug_tool = jlink
monitor_speed = 115200
lib_deps =
    https://github.com/Seeed-Studio/Seeed_Arduino_LSM6DS3.git